# http://docs.travis-ci.com/user/languages/android/
language: android

sudo: false
android:
  components:
    - tools # needs to be first to get new package versions
    - build-tools-25.0.0
    - platform-tools
jdk: oraclejdk8
os:
  - linux
#  - osx

before_install:
  - export ANDROID_OS=$ANDROID_TARGET
  - if [ "$JRUBY_JARS_VERSION" == "MASTER" ] || [ "$JRUBY_JARS_VERSION" == "STABLE" ] ; then rake get_jruby_jars_snapshots ; fi
  - STABLE=`ls jruby-jars-*.gem | head -n 1 | cut -f 3 -d'-' | sed s/\\.gem//`
  - MASTER=`ls jruby-jars-*.gem | tail -n 1 | cut -f 3 -d'-' | sed s/\\.gem//`
  - if [ "$JRUBY_JARS_VERSION" == "MASTER" ] ; then export JRUBY_JARS_VERSION=$MASTER ; fi
  - if [ "$JRUBY_JARS_VERSION" == "STABLE" ] ; then export JRUBY_JARS_VERSION=$STABLE ; fi
  - if [ "$ANDROID_TARGET" == "23" ] ; then ls -l $ANDROID_HOME/platforms ; rm -rf $ANDROID_HOME/platforms/android-1* ; ls -l $ANDROID_HOME/platforms ; ls -l $ANDROID_HOME/system-images ; rm -rf $ANDROID_HOME/system-images/android-1* ; ls -l $ANDROID_HOME/system-images ; fi

env:
  global:
    - DX_HEAP_SIZE=2048
    - RUBOTO_UPDATE_EXAMPLES=0

  matrix:


    - ANDROID_TARGET=23 RUBOTO_PLATFORM=STANDALONE TEST_PART=1of4 JRUBY_JARS_VERSION=1.7.25
    - ANDROID_TARGET=23 RUBOTO_PLATFORM=STANDALONE TEST_PART=2of4 JRUBY_JARS_VERSION=1.7.25
    - ANDROID_TARGET=23 RUBOTO_PLATFORM=STANDALONE TEST_PART=3of4 JRUBY_JARS_VERSION=1.7.25
    - ANDROID_TARGET=23 RUBOTO_PLATFORM=STANDALONE TEST_PART=4of4 JRUBY_JARS_VERSION=1.7.25
    - ANDROID_TARGET=19 RUBOTO_PLATFORM=STANDALONE TEST_PART=1of3 JRUBY_JARS_VERSION=1.7.25
    - ANDROID_TARGET=19 RUBOTO_PLATFORM=STANDALONE TEST_PART=2of3 JRUBY_JARS_VERSION=1.7.25
    - ANDROID_TARGET=19 RUBOTO_PLATFORM=STANDALONE TEST_PART=3of3 JRUBY_JARS_VERSION=1.7.25
    - ANDROID_TARGET=15 RUBOTO_PLATFORM=STANDALONE TEST_PART=1of3 JRUBY_JARS_VERSION=1.7.25
    - ANDROID_TARGET=15 RUBOTO_PLATFORM=STANDALONE TEST_PART=2of3 JRUBY_JARS_VERSION=1.7.25
    - ANDROID_TARGET=15 RUBOTO_PLATFORM=STANDALONE TEST_PART=3of3 JRUBY_JARS_VERSION=1.7.25

    - ANDROID_TARGET=19 RUBOTO_PLATFORM=STANDALONE TEST_PART=1of3 JRUBY_JARS_VERSION=1.7.13
    - ANDROID_TARGET=19 RUBOTO_PLATFORM=STANDALONE TEST_PART=2of3 JRUBY_JARS_VERSION=1.7.13
    - ANDROID_TARGET=19 RUBOTO_PLATFORM=STANDALONE TEST_PART=3of3 JRUBY_JARS_VERSION=1.7.13
    - ANDROID_TARGET=15 RUBOTO_PLATFORM=STANDALONE TEST_PART=1of3 JRUBY_JARS_VERSION=1.7.13
    - ANDROID_TARGET=15 RUBOTO_PLATFORM=STANDALONE TEST_PART=2of3 JRUBY_JARS_VERSION=1.7.13
    - ANDROID_TARGET=15 RUBOTO_PLATFORM=STANDALONE TEST_PART=3of3 JRUBY_JARS_VERSION=1.7.13

matrix:
  fast_finish: true
  allow_failures:
    - env: ANDROID_TARGET=23 RUBOTO_PLATFORM=STANDALONE TEST_PART=1of4 JRUBY_JARS_VERSION=1.7.25
    - env: ANDROID_TARGET=23 RUBOTO_PLATFORM=STANDALONE TEST_PART=2of4 JRUBY_JARS_VERSION=1.7.25
    - env: ANDROID_TARGET=23 RUBOTO_PLATFORM=STANDALONE TEST_PART=3of4 JRUBY_JARS_VERSION=1.7.25
    - env: ANDROID_TARGET=23 RUBOTO_PLATFORM=STANDALONE TEST_PART=4of4 JRUBY_JARS_VERSION=1.7.25

script:
  - rvm use 2.3.1 --install
  - ./run_tests.sh

notifications:
  irc:
    channels:
      - "irc.freenode.org#ruboto"
    use_notice: true
    skip_join: true

  webhooks:
    urls:
      - https://webhooks.gitter.im/e/fe0d532fe5bef5b7288c
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
